version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
      - ./utf8mb4.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sandbox
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
    - 3306:3306
    networks:
      - mysql_pma
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - mysql_pma
networks:
  mysql_pma:
volumes:
  data:

